"""
Async trajectory buffer.

Decouples the rollout producer from the training consumer.
Implements off-policyness control: trajectories generated by a policy
version too far from the current training policy are discarded.

This mirrors AReaL's max_head_offpolicyness parameter.
"""
from __future__ import annotations

import asyncio
import time
from collections import deque
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from nano_areal.archon.trainer import Trajectory


@dataclass
class BufferStats:
    total_produced: int = 0
    total_consumed: int = 0
    total_discarded: int = 0
    wait_time_s: float = 0.0


class AsyncTrajectoryBuffer:
    """
    Thread-safe (asyncio) trajectory buffer with off-policyness filtering.

    Producer (rollout worker):  await buffer.put(trajectory)
    Consumer (train worker):    batch = await buffer.get_batch(n)
    """

    def __init__(
        self,
        max_head_offpolicyness: int = 4,
        maxsize: int = 512,
    ):
        self.max_head_offpolicyness = max_head_offpolicyness
        self._queue: asyncio.Queue = asyncio.Queue(maxsize=maxsize)
        self._current_policy_version: int = 0
        self.stats = BufferStats()

    # ------------------------------------------------------------------
    # Producer API
    # ------------------------------------------------------------------

    async def put(self, trajectory: "Trajectory"):
        """
        Add a trajectory to the buffer.
        Blocks if the buffer is full (back-pressure on rollout).
        """
        await self._queue.put(trajectory)
        self.stats.total_produced += 1

    def put_nowait(self, trajectory: "Trajectory"):
        """Non-blocking put; raises asyncio.QueueFull if buffer is full."""
        self._queue.put_nowait(trajectory)
        self.stats.total_produced += 1

    # ------------------------------------------------------------------
    # Consumer API
    # ------------------------------------------------------------------

    def update_policy_version(self, version: int):
        """Called by the trainer after each gradient step."""
        self._current_policy_version = version

    async def get_batch(
        self,
        n: int,
        timeout: float = 30.0,
    ) -> list["Trajectory"]:
        """
        Collect `n` valid trajectories from the buffer.

        Trajectories whose policy version is too stale
        (current_version - traj.version > max_head_offpolicyness)
        are silently discarded.

        Blocks until `n` valid trajectories are collected or timeout.
        """
        batch: list = []
        deadline = time.monotonic() + timeout

        while len(batch) < n:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                break
            try:
                traj = await asyncio.wait_for(self._queue.get(), timeout=min(remaining, 2.0))
            except asyncio.TimeoutError:
                continue

            version_gap = self._current_policy_version - traj.policy_version
            if self.max_head_offpolicyness > 0 and version_gap > self.max_head_offpolicyness:
                self.stats.total_discarded += 1
                continue

            batch.append(traj)
            self.stats.total_consumed += 1

        return batch

    # ------------------------------------------------------------------
    # Sync mode (max_head_offpolicyness == 0)
    # ------------------------------------------------------------------

    async def get_batch_sync(self, n: int) -> list["Trajectory"]:
        """
        Blocking collect for sync mode: waits until exactly n trajectories
        are available regardless of version.
        """
        batch = []
        while len(batch) < n:
            traj = await self._queue.get()
            batch.append(traj)
            self.stats.total_consumed += 1
        return batch

    # ------------------------------------------------------------------
    # Inspection
    # ------------------------------------------------------------------

    @property
    def qsize(self) -> int:
        return self._queue.qsize()

    @property
    def maxsize(self) -> int:
        return self._queue.maxsize

    def __repr__(self) -> str:
        return (
            f"AsyncTrajectoryBuffer("
            f"size={self.qsize}/{self.maxsize}, "
            f"produced={self.stats.total_produced}, "
            f"consumed={self.stats.total_consumed}, "
            f"discarded={self.stats.total_discarded})"
        )
